### PR TITLE
docs: Rework the adhoc examples to cover all the adhoc modes.

### PR DESCRIPTION
**Pull request by abeaumont**

### CODE REVIEW

**Comment by petethepig** [comment]
@abeaumont can you please fix the linting issue?

**Comment by abeaumont** [comment]
I disabled linting for the whole `examples` directory.

**Comment by petethepig** [comment]
@abeaumont now windows tests are not happy :)

**Comment by abeaumont** [comment]
Yes, sorry about that. They should be fixed now, but it still fails randomly, it seems some tests are flaky in windows.

**Comment by abeaumont** [comment]
I had enabled race detection and apparently, the windows runner runs out of memory in that case. I have removed race detection again.

**Pull request merged**
