### PR TITLE
Optimise tree representation

### PR DESCRIPTION
**Pull request by kolesnikovae**
This PR is aimed to optimise allocations related to tree operations. Another aspect is the number of live objects on heap: with the new tree representation, it is expected that only one object will be allocated per node (although, there is a way to get rid of the allocation, it is left for the further work).

## Compatibility

The changes affect the tree serialisation format. V1 format (the current one) is still supported.

**IMPORTANT**: server downgrade is not supported.

## Benchmarking

Despite the fact that the results demonstrate very subtle difference in terms of CPU time, the overall performance will improve due to decrease of GC time and reduced number of allocations.

As an input set a tree consisting of ~1.2K nodes has been taken.

```
goos: darwin
goarch: amd64
pkg: github.com/pyroscope-io/pyroscope/pkg/storage/tree
cpu: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
```

Before: (v0.0.41)
```
BenchmarkInsert-4            758           1438849 ns/op         1535249 B/op      10622 allocs/op
BenchmarkClone-4            8174            158419 ns/op           86080 B/op       2245 allocs/op
BenchmarkMerge-4           20598             61485 ns/op           25552 B/op        281 allocs/op
```
After:
```
BenchmarkInsert-4            818           1290461 ns/op          778604 B/op       1196 allocs/op
BenchmarkClone-4            9939            133340 ns/op          263632 B/op       1053 allocs/op
BenchmarkMerge-4           50539             25963 ns/op           11568 B/op         95 allocs/op
BenchmarkTruncate-4         5084            209022 ns/op          398184 B/op         14 allocs/op
```

### CODE REVIEW

**Comment by kolesnikovae** [comment]
create server

**Comment by kolesnikovae** [comment]
create server

**Comment by kolesnikovae** [comment]
create server

**Comment by kolesnikovae** [comment]
create server

**Comment by kolesnikovae** [comment]
Reduced fixture size (tree_v2.txt) to not trigger max-file-check.

**Comment by kolesnikovae** [comment]
retest

**Comment by kolesnikovae** [comment]
Not ready for merge: still in test.

**Comment by petethepig** [comment]
We've decided to close this one due to the fact that performance improvements from this change are minor, but the code is now more complex.

**Pull request closed without merging**
