### PR TITLE
serve assets gzipped #342

### PR DESCRIPTION
**Pull request by gawicks**

### CODE REVIEW

**Comment by gawicks** [comment]
Setting this to WIP till I've written some tests

**Comment by gawicks** [comment]
@petethepig I'd like some feedback on the use of [klauspost/compress](https://github.com/klauspost/compress) library.

**Comment by petethepig** [comment]
It looks good! I tried running it too and it seems to be working as expected. My original plan was to only enable it for everything in `/assets`, but then I thought about it and I figured this even better actually.

**Comment by petethepig** [comment]
@gawicks Oh, and regarding the library, I do think it makes sense to use it here.

**Comment by gawicks** [comment]
@petethepig Thanks! I've finished adding tests. The PR is ready for review.

**Review by petethepig — APPROVED** [review]

**Comment by gawicks** [comment]
Yay!

**Pull request merged**
