### PR TITLE
refactor(webapp): Update time selector dropdown styling

### PR DESCRIPTION
**Pull request by pavelpashkovsky**
## Brief
- https://github.com/pyroscope-io/pyroscope/issues/1632
## Changes
image

### CODE REVIEW

**Comment by eh-am** [comment]
I think background color should be straight up white, similar to annotations here 
image

Then it's clear it something you can actually interact with.

**Comment by eh-am** [comment]
Also we should reuse the `Input` element from `@ui`

**Comment by pavelpashkovsky** [comment]
@eh-am 

> I think background color should be straight up white, similar to annotations here image
> 
> Then it's clear it something you can actually interact with.

am I on a right way (according to colors)?
image

**Comment by eh-am** [comment]
@pavelpashkovsky i was thinking for inputs (since that's what we already do), but dropdowns are definitely more trickier so i wouldn't touch that yet :(

**Review by eh-am — APPROVED** [review]

**Pull request merged**
