### PR TITLE
feat(flamegraph): allow sorting by diff percentage

### PR DESCRIPTION
**Pull request by dogfrogfog**
## Brief
- https://github.com/pyroscope-io/pyroscope/issues/1770

## Changes
- add ability to sort by diff column

### CODE REVIEW

**Comment by dogfrogfog** [comment]
is `infinity` value expected here ? 

https://user-images.githubusercontent.com/47758224/204783752-9887d6f1-efee-4016-ba71-d9f24c3c2197.mov

**Comment by eh-am** [comment]
>is infinity value expected here ?
I don't think so, it looks like it should be considered "new" no?

**Comment by dogfrogfog** [comment]
> > is infinity value expected here ?
> > I don't think so, it looks like it should be considered "new" no?

ye..i will fix it

**Review by eh-am — APPROVED** [review]

**Pull request merged**
