### PR TITLE
fix: #722 Do not allow querying in the future

### PR DESCRIPTION
**Pull request by naftalimurgor**
Hello @eh-am 

fix: [#722](https://github.com/pyroscope-io/pyroscope/issues/722)

Greetings! I managed to work out a solution for querying a future date regression as mentioned in this [#722](https://github.com/pyroscope-io/pyroscope/issues/722)

- Add check to `CustomDatePicker` component to check if the selected date is into the future by comparing the date selected to the current date constructed from the current timestamp
- Toggle `disabled` prop of `Button` component in `CustomDatePicker` based on whether the `Until` input is into a future date

Preview:
https://user-images.githubusercontent.com/37052032/154798372-33ae1aa4-bf60-4634-99e1-aa01b985468b.mp4

Please let me know of any issues,
Best,

Naftali

### CODE REVIEW

**Review by eh-am — COMMENTED** [review]
Hello, thank you for your contribution!

Now that I am playing with this feature I realize the original requirements don't make a lot of sense sense.

1. If you are querying into the future, then simply no data will be returned from the server. Which is totally fine!

2. It may be useful to allow querying into the future: when you know what's the stop time.
For example: let's say I will start some load testing for 30 minutes. Then it makes sense querying into the future, since I know what's the stop time: 30 minutes from now.

Therefore I will close this PR and the issue. I apologize for the inconvenience.
There are other good first issues, specially for the frontend!
https://github.com/pyroscope-io/pyroscope/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

Thank you!

**Comment by naftalimurgor** [comment]
Thanks @eh-am for the feedback. Will keep looking for other issues to work on

Thank you!

**Pull request closed without merging**
