### PR TITLE
feat(webapp): remove all templates

### PR DESCRIPTION
**Pull request by shaleynikov**
Removed:
* forbidden  
* welcome 
* redirect

### CODE REVIEW

**Review by eh-am — COMMENTED** [review]
One thing I don't understand, how is one redirected to the forbidden page now?

**Comment by shaleynikov** [comment]
> One thing I don't understand, how is one redirected to the forbidden page now?
I think the only way is here

https://github.com/pyroscope-io/pyroscope/blob/401ecc2977b9467f78adf06cfa60ec41bbfd100b/pkg/server/login.go#L211-L218

**Comment by petethepig** [comment]
Works good, great job!

**Review by petethepig — APPROVED** [review]
Works good, great job!

**Pull request merged**
