### PR TITLE
feat(webapp): Make explore page show precise numbers in table

### PR DESCRIPTION
**Pull request by pavelpashkovsky**
## Brief
- https://github.com/pyroscope-io/pyroscope/issues/1681

## Changes
- DEMO: https://pr-1695.pyroscope.io/
image

### CODE REVIEW

**Comment by eh-am** [comment]
Can you add few tests to this
https://github.com/pyroscope-io/pyroscope/blob/0db1872abf49aaa3c3cfa3bd7d79d1502ba3562c/packages/pyroscope-flamegraph/src/format/format.spec.ts ? It's a bit hard to grasp the logic by just looking at the code.

**Comment by Rperry2174** [comment]
also not sure how hard this is to do, but can you make it so that all of the decimal places are alligned?

**Comment by Rperry2174** [comment]
adding this for reference: https://alistapart.com/article/web-typography-tables/

**Review by Rperry2174 — APPROVED** [review]
LGTM

**Pull request merged**
