### PR TITLE
Import pyroscope version from package.json

### PR DESCRIPTION
**Pull request by abaali**

### CODE REVIEW

**Comment by petethepig** [comment]
Hi @abaali !

Thanks for the PR. Could you also remove `PYROSCOPE_VERSION` from here https://github.com/pyroscope-io/pyroscope/blob/master/scripts/webpack/webpack.common.js#L181 ? That's where it was coming from before. I like your way much better, I just want to make sure we clean up the old one to avoid confusion.

**Review by petethepig — APPROVED** [review]
LGTM

**Review by petethepig — CHANGES_REQUESTED** [review]
See the comment above

**Comment by abaali** [comment]
@petethepig 
I had some issues adding commits to this pr so I will open a new one with the changes.

**Pull request closed without merging**
