### PR TITLE
feat: added tooltip for timeline selection

### PR DESCRIPTION
**Pull request by shaleynikov**
This is a contribution for  #99

### CODE REVIEW

**Comment by petethepig** [comment]
Looks great! The only thing I could find is it should add a zero before 5 in `10:05`
Screen Shot 2022-01-14 at 10 55 09 AM

**Comment by Rperry2174** [comment]
Hey @shaleynikov everything looks good here. Could you add a simple unit test that:
- Creates a hover event
- Checks that the tooltip exists on-hover

**Comment by Rperry2174** [comment]
hey @shaleynikov currently when selecting a time range on the graph, there are two tooltips on the bottom while the mouse is down. 

Can you make it so that there is only one (at the current location of the mouse)

**Pull request merged**
