### PR TITLE
Crosshair implementation

### PR DESCRIPTION
**Pull request by cmonez**
-Implemented crosshair functionality when hovering over timeline graph (issue [51](https://github.com/pyroscope-io/pyroscope/issues/51))
-Used blue to make crosshair pop when overlayed the gold bars
crosshair

### CODE REVIEW

**Comment by petethepig** [comment]
Looks awesome!

It would be cool if the cursor also changed to crosshair, I know there's a CSS option for that:

IMG_5700 copy

**Comment by Rperry2174** [comment]
I agree thanks @cmonez !!! I also think that we should change the color to red instead of blue so that it stands out a little bit more. Can you change it to this red: `#C3170D`?

**Comment by cmonez** [comment]
will change that to #C3170D , @petethepig so you want the cursor to disappear, and just be represented by the crosshair instead, correct? will work on this rn.

**Comment by Rperry2174** [comment]
Yeah just to be clear so instead of your typical cursor it will be a _cross_ instead:

So the red line should still show, but instead of this:
image

when you move your mouse it will look like this:
image

**Comment by cmonez** [comment]
kk
crosshair-cross

**Review by Rperry2174 — APPROVED** [review]
Looks 🔥!!! Thanks so much. I think this will help usability a lot and get people to utilize the timeline more with these indicators that they can interact with it.

**Pull request merged**
