### PR TITLE
Refactor and Modernize Webapp

### PR DESCRIPTION
**Pull request by LouisInFlow**
* Enable JSX Lint
* Convert class components to function components
* Will refactor FlameGraphRenderer in follow-up

### CODE REVIEW

**Comment by LouisInFlow** [comment]
Resolve #27

**Comment by Rperry2174** [comment]
Thanks @LouisInFlow can you please explain some of the benefits of switching from class components to functional components?

**Comment by LouisInFlow** [comment]
Function components are a solution the React core team developed to solve problems discovered through the many years of seeing React out in the wild, it's where React is going and preferred by the core team. Class components maintained for backwards compatibility only. 

The main things are: 

1.  Lower complexity of component (no this, no constructor, [more intuitive life-cycle control](https://reactjs.org/docs/hooks-effect.html))
2. [React Hooks](https://reactjs.org/docs/hooks-intro.html ) - share stateful logic easier/cleaner, [this is how it works with redux](https://react-redux.js.org/api/hooks)
3. Better performance and fits JS model of programming better (JS doesn't have native classes, ES6 classes are sugar on top of prototype inheritance, JS/React is more declarative and functional programming.)
4. Easier to test (props are arguments and the output is jsx)
5. It's not either/or, codebase can be some class/some function components. 
6. New major features will only work with function components, like the [currently experimental concurrent mode (better user experience when fetching data)
](https://reactjs.org/docs/concurrent-mode-intro.html)

**Review by Rperry2174 — CHANGES_REQUESTED** [review]
Hey @LouisInFlow, I noticed an error with the dateRangePicker component:

This is partially not working in the current version (#31), but somehow was made worse in this version:
When you start from the `dateRangePicker`:
Screen Shot 2021-01-22 at 8 00 32 PM

And then you "delete" the "1" from "now - 1h", then it breaks the page. This is probably a result of our initial code being more forgiving of the bug, but either way this version is worse because before it was a no-op and now it breaks the page. Could you either:

- Maintain the current functionality of just having them be no-ops and well fix in a follow-up
- Fix the button so that they work as intended

Also the refresh button no longer works. When I click it i get this error in the console:
image

**Comment by LouisInFlow** [comment]
resolve #31

**Review by Rperry2174 — APPROVED** [review]
LGTM 🔥  Thanks a ton @LouisInFlow

**Pull request merged**
