### PR TITLE
Enhancement/split flamegraphrenderer

### PR DESCRIPTION
**Pull request by Loggy**

### CODE REVIEW

**Comment by Rperry2174** [comment]
Thanks for the updates @Loggy ! We recently added Cyprus testing and it looks like one is failing. 
1. Can you make sure this branch is up to date with master?
2. Can you also add a test that checks for the following scenario: when a new app is selected in the dropdown that the flamegraph renderer updates?

You can see more details here:
image

Also @eh-am might be able to answer questions about Cyprus in general if you have any

**Comment by Rperry2174** [comment]
Hey @Loggy I think something might have gone wrong with the rebase (or maybe it needs to be rebased still)


Here is our staging version: https://demo-dev.pyroscope.io/comparison?name=cart.service.dotnet.cpu%7B%7D&from=1630441060&leftFrom=1630441133&leftUntil=1630441428&rightFrom=1630441437&rightUntil=1630441770&until=1630441960
image


and here is your PR version 
https://pr-360.pyroscope.cloud/comparison-diff?name=cart.service.dotnet.cpu%7B%7D&from=1630441060&leftFrom=1630441133&leftUntil=1630441428&rightFrom=1630441437&rightUntil=1630441770&until=1630441960
image


(btw you can find a link to your PR server shown above here):
image
H

**Comment by Rperry2174** [comment]
Also make sure to check the Diff view as well:

Demo App: https://demo-dev.pyroscope.io/comparison-diff
image

This PR: https://pr-360.pyroscope.cloud/comparison-diff
image

**Comment by Rperry2174** [comment]
Hey @Loggy noticed a bug where the tooltip from the left flamegraph goes behind the right flamegraph: 
image

**Comment by Rperry2174** [comment]
Also there is a random dot that appears on page load. I think this is related to the tooltip because it disappears when we use the tooltip, but I'm not sure:
image

**Comment by petethepig** [comment]
jenkins, create a review app server please

**Pull request merged**
