### PR TITLE
Improves logging in gospy agent

### PR DESCRIPTION
**Pull request by petethepig**
work in progress

### CODE REVIEW

**Comment by rayanbettis** [comment]
How am i going to do z(pull request) I'm just a beginner

**Comment by rayanbettis** [comment]
> work in progress

**Comment by scbizu** [comment]
https://github.com/pyroscope-io/pyroscope/runs/1986055083#step:4:6

CI seems broken.

**Comment by petethepig** [comment]
@scbizu Yeah, this is work in progress, I'm not merging it yet. But thanks for letting me know!

**Comment by scbizu** [comment]
Looks great , when will it get merged ?

**Comment by petethepig** [comment]
@scbizu Just merged, thanks your patience :)

**Pull request merged**
