### PR TITLE
Added a date and time picker

### PR DESCRIPTION
**Pull request by abaali**
this pull request is related to issue  [#47](https://github.com/pyroscope-io/pyroscope/issues/47)

### CODE REVIEW

**Review by Rperry2174 — APPROVED** [review]
Thanks @abaali this is a huge improvement over the previous version!

**Comment by LouisInFlow** [comment]
Great solution @abaali!

**Comment by LouisInFlow** [comment]
Screen Shot 2021-01-31 at 8 46 48 AM

**Comment by LouisInFlow** [comment]
@abaali I get the below error when using the date picker for the second custom date range selection.
Screen Shot 2021-01-31 at 8 50 44 AM

**Comment by abaali** [comment]
Hi @LouisInFlow 
I didn't notice this error when earlier thank you for pointing it out
i will try to fix it soon

**Pull request merged**
