### PR TITLE
build: install dev dependencies when running in docker

### PR DESCRIPTION
**Pull request by eh-am**

### CODE REVIEW

**Comment by eh-am** [comment]
Meh 

```
#122 [linux/arm64 js-builder 10/11] RUN --mount=type=cache,target=/usr/local/share/.cache/yarn/v6 yarn install --frozen-lockfile
#122 sha256:0a7445552fb3635da4d2ea54a0a51f4db1c630457bf1d1ebf570dba241d44deb
#122 50.95 [5/5] Building fresh packages...
#122 52.72 error /opt/pyroscope/node_modules/estimo: Command failed.
#122 52.72 Exit code: 1
#122 52.72 Command: node ./scripts/find-chrome-binary.js
#122 52.72 Arguments: 
#122 52.72 Directory: /opt/pyroscope/node_modules/estimo
#122 52.72 Output:
#122 52.72 /bin/sh: undefined: not found
#122 52.72 The chromium binary is not available for arm64.
#122 52.72 If you are on Ubuntu, you can install with: 
#122 52.72 
#122 52.72  sudo apt install chromium
#122 52.72 
#122 52.72 
#122 52.72  sudo apt install chromium-browser
#122 52.72 
#122 52.72 /opt/pyroscope/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserFetcher.js:115
#122 52.72                     throw new Error();
#122 52.72                     ^
#122 52.72 
#122 52.72 Error
#122 52.72     at /opt/pyroscope/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserFetcher.js:115:27
#122 52.72     at FSReqCallback.oncomplete (fs.js:192:21)
#122 52.72 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```


Let's use https://github.com/pyroscope-io/pyroscope/pull/1350 instead

**Review by Rperry2174 — APPROVED** [review]
Sounds good feel free to merge/close whichever one when you're ready

**Comment by eh-am** [comment]
sorry forgot to close this one

**Pull request closed without merging**
