### PR TITLE
feat: reuse Table component everywhere

### PR DESCRIPTION
**Pull request by dogfrogfog**
## Brief
- https://github.com/pyroscope-io/pyroscope/issues/1391
    - create reusable table component
    - use new table component for existed tables
## Changes
- all tables use same Table ui component
- new ui component - Table
- add ability to create custom tables by passing props
- add useTableSort  hook to make tables sortable (pass exported props to Table, no more actions)
## Concerns
- _

https://user-images.githubusercontent.com/47758224/185132348-cf12f792-b2bf-4c86-a9f4-ff0a0856e432.mov

### CODE REVIEW

**Comment by eh-am** [comment]
Can you add an example to Storybook please!

**Review by Rperry2174 — APPROVED** [review]
Going to merge now, lets follow up later with a PR to make the tables uniform (i.e. they should all look mostly the same)

**Pull request merged**
