### PR TITLE
fix(webapp | flamegraph): toolbar overlaps annotation

### PR DESCRIPTION
**Pull request by pavelpashkovsky**
## Brief
- https://github.com/pyroscope-io/pyroscope/issues/1780

## Changes

DEMO: https://pr-1785.pyroscope.io/

image

### CODE REVIEW

**Comment by pavelpashkovsky** [comment]
I fixed this issue by removing z-index from Toolbar styles. My testing showed that it didn't cause any problems. @eh-am, do you have any reason to have z-index for flamegraph's Toolbar ? _bc I could forget about some edge case why we need setting z-index.._

**Comment by eh-am** [comment]
It was introduced here https://github.com/pyroscope-io/pyroscope/pull/1754 by @dogfrogfog 
So @dogfrogfog, can we remove that z-index?

**Comment by dogfrogfog** [comment]
i think this can be removed

**Review by dogfrogfog — APPROVED** [review]

**Pull request merged**
