### PR TITLE
feat: add ticks to x and y-axis

### PR DESCRIPTION
**Pull request by dogfrogfog**
## Brief
- https://github.com/pyroscope-io/pyroscope/issues/1553

## Changes
- add ticks to x and y-axis
Screenshot 2022-09-27 at 13 22 01

## Concerns
-

### CODE REVIEW

**Comment by Rperry2174** [comment]
lets remove the first tick on the x-axis and then also add borders to x and y axis
image

**Comment by eh-am** [comment]
Also does the timestamps there change appropriately when formatting as UTC?

**Comment by dogfrogfog** [comment]
https://user-images.githubusercontent.com/47758224/192755557-897b5f95-a688-43cc-9218-56f6a1c82d97.mov

**Comment by dogfrogfog** [comment]
> Also does the timestamps there change appropriately when formatting as UTC?

yes, for x-axis values....but wont format value in heatmap tooltip (will be inplemented [here](https://github.com/pyroscope-io/pyroscope/pull/1559/files#diff-2c20d81edf9268c74557d826a0a4f5ec89079fa170ecc4520751cbd28abdae1bR31) due to potential conflicts)

**Review by Rperry2174 — APPROVED** [review]
lgtm

**Pull request merged**
