### PR TITLE
Allow enabling Badger's truncate option

### PR DESCRIPTION
**Pull request by czeslavo**
Motivation for this PR is a production case we had in our system. After a crash Pyroscope server isn't able to boot up due to following error: 

```
panic: During db.vlog.open: Value log truncate required to run DB. This might result in data loss

goroutine 1 [running]:
github.com/pyroscope-io/pyroscope/pkg/cli.startServer(0xc000150a00)
        github.com/pyroscope-io/pyroscope/pkg/cli/cli.go:318 +0x5f1
github.com/pyroscope-io/pyroscope/pkg/cli.Start.func2(0x15aa160, 0xc000032018, 0xc00000e0b0, 0x0, 0x0, 0xc000118660, 0x0)
        github.com/pyroscope-io/pyroscope/pkg/cli/cli.go:273 +0x5f
github.com/peterbourgon/ff/v3/ffcli.(*Command).Run(0xc000132b00, 0x15aa160, 0xc000032018, 0x0, 0x0)
        github.com/peterbourgon/ff/v3@v3.0.0/ffcli/command.go:153 +0x1b2
github.com/peterbourgon/ff/v3/ffcli.(*Command).Run(0xc000132dc0, 0x15aa160, 0xc000032018, 0x0, 0x0)
        github.com/peterbourgon/ff/v3@v3.0.0/ffcli/command.go:157 +0x125
github.com/peterbourgon/ff/v3/ffcli.(*Command).ParseAndRun(0xc000132dc0, 0x15aa160, 0xc000032018, 0xc00000e0b0, 0x1, 0x1, 0x240, 0x250)
        github.com/peterbourgon/ff/v3@v3.0.0/ffcli/command.go:169 +0x7e
github.com/pyroscope-io/pyroscope/pkg/cli.Start(0xc000150a00, 0x15, 0xc000150a00)
        github.com/pyroscope-io/pyroscope/pkg/cli/cli.go:311 +0xb9a
main.main()
        github.com/pyroscope-io/pyroscope/cmd/pyroscope/main.go:13 +0x56
``` 

Badger needs `Truncate` option to be enabled to fix the corrupted data: https://github.com/dgraph-io/badger/issues/1353.

### CODE REVIEW

**Comment by czeslavo** [comment]
The failing test doesn't seem to be connected to my changes, I don't know how to rerun them though.

**Comment by petethepig** [comment]
Thanks for the patch @czeslavo !

Yeah, the test failure is unrelated, I think it's just a flaky test.

RE truncate.. I think maybe we should even default to `true` in this case. Let me do some research on this.

**Review by petethepig — APPROVED** [review]
I'm gonna merge this and make it true by default in the follow up commit.

**Comment by czeslavo** [comment]
@petethepig thanks for a quick merge! Could we have a release with the changes?

**Comment by petethepig** [comment]
@czeslavo Yes, I'll release tonight, in a few hours. Thanks for waiting!

**Comment by petethepig** [comment]
@czeslavo I just released it https://pyroscope.io/downloads/

**Comment by czeslavo** [comment]
> @czeslavo I just released it (0.0.29) https://pyroscope.io/downloads/

Thanks, works as expected :)

**Pull request merged**
