### PR TITLE
feat: add single, comparison, diff tabs to heatmap page

### PR DESCRIPTION
**Pull request by dogfrogfog**
## Brief
- https://github.com/pyroscope-io/pyroscope/issues/1561

## Changes
- add tabs with single/comparison/diff flamegraphs
- rename TimelineTitle component to ChartTitle
- add new props to ChartTitle component

demo link: https://pr-1672.pyroscope.io/exemplars/single?query=rideshare-app-golang.cpu%7B%7D

https://user-images.githubusercontent.com/47758224/200853484-46e0ef0a-2626-456d-8768-19e86c0fd70c.mov

adhoc tabs 
Screenshot 2022-11-03 at 11 36 00

## Concerns
-

### CODE REVIEW

**Review by eh-am — APPROVED** [review]

**Review by eh-am — APPROVED** [review]
Looks good! Added a small comment, but nothing major.

**Comment by Rperry2174** [comment]
For comparison page have a few styling tweaks. I do think it's hard to understand what's going on to someone who is new to the page so I added a couple of elements to hopefully help with that. We can continue to refine these over time, but for now:

heatmap_comparison_mockup_02

- Added titles "Selection-included exemplar flamegraph" and "Selection-excluded exemplar flamegraph"
- Added svg squares to go next to the titles (included at bottom of this comment)
- Added "info" buttons to help explain what each of those titles mean in more detail
- Added tootltip with info explanation (on hover of the "info") buttons

heatmap_comparison_mockup_02_selection_excluded
heatmap_comparison_mockup_02_selection_included

**Pull request merged**
