### PR TITLE
chore(webapp): Moving tabs to MUI

### PR DESCRIPTION
**Pull request by pavelpashkovsky**
## Brief
- https://github.com/pyroscope-io/pyroscope/issues/1753

## Changes
 - Tabs were moved from `react-tabs` to `MUI Tabs`. `react-tabs` was removed from project.
 
 DEMO: https://pr-1763.pyroscope.io/

### CODE REVIEW

**Comment by pavelpashkovsky** [comment]
@eh-am, I disabled ripple effect and hid the indicator

https://user-images.githubusercontent.com/7372044/204468309-ad5207e7-b045-409b-a3de-8d98f9b849f4.mp4

**Comment by eh-am** [comment]
👍

**Pull request merged**
